export const CHANGE_LOCALE_VALUE = 'CHANGE_LOCALE_VALUE';
export const UPDATE_ACCESS_TOKEN_ACTION = 'UPDATE_ACCESS_TOKEN_ACTION';
export const AUTHENTICATE_USER_ACTION = 'AUTHENTICATE_USER_ACTION';
export const RESTORE_GAME_STATUS = 'RESTORE_GAME_STATUS';
